type_strengths = {
    "bug": ["Grass", "Dark", "Psychic"],
    "dark": ["Ghost", "Psychic"],
    "dragon": ["Dragon"],
    "electric": ["Flying", "Water"],
    "fairy": ["Fighting", "Dark", "Dragon"],
    "fighting": ["Dark", "Ice", "Normal", "Rock", "Steel"],
    "fire": ["Bug", "Grass", "Ice", "Steel"],
    "flying": ["Bug", "Fighting", "Grass"],
    "ghost": ["Ghost", "Psychic"],
    "grass": ["Ground", "Rock", "Water"],
    "ground": ["Electric", "Fire", "Poison", "Rock", "Steel"],
    "ice": ["Dragon", "Flying", "Grass", "Ground"],
    "normal": [],
    "poison": ["Fairy", "Grass"],
    "psychic": ["Fighting", "Poison"],
    "rock": ["Bug", "Fire", "Flying", "Ice"],
    "steel": ["Fairy", "Ice", "Rock"],
    "water": ["Fire", "Ground", "Rock"]
}

type_weaknesses = {
    "bug": ["Fire", "Flying", "Rock"],
    "dark": ["Bug", "Fairy", "Fighting"],
    "dragon": ["Dragon", "Fairy", "Ice"],
    "electric": ["Ground"],
    "fairy": ["Poison", "Steel"],
    "fighting": ["Fairy", "Flying", "Psychic"],
    "fire": ["Ground", "Rock", "Water"],
    "flying": ["Electric", "Ice", "Rock"],
    "ghost": ["Dark", "Ghost"],
    "grass": ["Bug", "Fire", "Flying", "Ice", "Poison"],
    "ground": ["Grass", "Ice", "Water"],
    "ice": ["Fighting", "Fire", "Rock", "Steel"],
    "normal": ["Fighting"],
    "poison": ["Ground", "Psychic"],
    "psychic": ["Bug", "Dark", "Ghost"],
    "rock": ["Fighting", "Grass", "Ground", "Steel", "Water"],
    "steel": ["Fighting", "Fire", "Ground"],
    "water": ["Electric", "Grass"]
}
